<x-app-layout>
    <x-slot name="header"><div class="flex items-center justify-between"><h2 class="text-xl font-semibold leading-tight text-gray-800">お問い合わせ管理</h2><div class="flex gap-2 text-sm"><a class="rounded px-3 py-2 {{ $status === '' ? 'bg-gray-800 text-white' : 'bg-white text-gray-600' }}" href="{{ route('contact-inquiries.index') }}">すべて</a><a class="rounded px-3 py-2 {{ $status === 'unread' ? 'bg-gray-800 text-white' : 'bg-white text-gray-600' }}" href="{{ route('contact-inquiries.index', ['status' => 'unread']) }}">未返信</a><a class="rounded px-3 py-2 {{ $status === 'replied' ? 'bg-gray-800 text-white' : 'bg-white text-gray-600' }}" href="{{ route('contact-inquiries.index', ['status' => 'replied']) }}">返信済み</a></div></div></x-slot>
    <div class="py-12"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        @if (session('status')) <div class="mb-6 rounded-md bg-green-50 p-4 text-sm text-green-700">{{ session('status') }}</div> @endif
        <div class="overflow-hidden bg-white shadow-xl sm:rounded-lg">
            @if ($inquiries->isEmpty()) <div class="p-8 text-center text-gray-500">お問い合わせはありません。</div>
            @else <div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200"><thead class="bg-gray-50"><tr><th class="px-6 py-3 text-left text-xs font-medium uppercase text-gray-500">状態</th><th class="px-6 py-3 text-left text-xs font-medium uppercase text-gray-500">送信者</th><th class="px-6 py-3 text-left text-xs font-medium uppercase text-gray-500">件名・本文</th><th class="px-6 py-3 text-left text-xs font-medium uppercase text-gray-500">受付日時</th><th class="px-6 py-3"></th></tr></thead><tbody class="divide-y divide-gray-200">
                @foreach ($inquiries as $inquiry)<tr><td class="whitespace-nowrap px-6 py-4"><span class="rounded-full px-2 py-1 text-xs {{ $inquiry->status === 'replied' ? 'bg-green-100 text-green-700' : 'bg-yellow-100 text-yellow-800' }}">{{ $inquiry->status === 'replied' ? '返信済み' : '未返信' }}</span></td><td class="px-6 py-4"><div class="font-medium text-gray-900">{{ $inquiry->name }}</div><div class="text-sm text-gray-500">{{ $inquiry->email }}</div></td><td class="px-6 py-4"><div class="font-medium text-gray-900">{{ $inquiry->subject ?: '（件名なし）' }}</div><div class="mt-1 max-w-xl truncate text-sm text-gray-500">{{ $inquiry->message }}</div></td><td class="whitespace-nowrap px-6 py-4 text-sm text-gray-500">{{ $inquiry->created_at->format('Y/m/d H:i') }}</td><td class="whitespace-nowrap px-6 py-4 text-right"><a class="text-sm text-indigo-600 hover:text-indigo-900" href="{{ route('contact-inquiries.show', $inquiry) }}">確認・返信</a></td></tr>@endforeach
            </tbody></table></div> @endif
        </div>
        <div class="mt-6">{{ $inquiries->links() }}</div>
    </div></div>
</x-app-layout>
